### PR TITLE
DML Commands

### PR DESCRIPTION
**Pull request by Ahamed1846**
1. In this commit, "MySQL_queries" has been updated with DML queries for inserting and updating the data.
2. I have done an explanation of this PR [here](https://drive.google.com/file/d/1wQZFgmAyqKiZHkvENB3vvu4DBiEgW2dp/view?usp=sharing).

### CODE REVIEW

**Comment by th3c0d3br34ker** [comment]
hey @Ahamed1846, consider using a public platform like loom for submitting self-viva. The above link is not accessible.

please re-submit with the correct links.

thanks.

**Comment by Ahamed1846** [comment]
Hey @th3c0d3br34ker, I have changed the access from anyone with a Kalvium community ID to anyone with the link. I believe you should now be able to view the video. I'll try to use Loom or a similar platform next time.

**Comment by th3c0d3br34ker** [comment]
thanks @Ahamed1846 for your submission. the self-viva is satisfactory for `DML Commands.`

please re-submit it with a more detailed explanation.

please avoid using G-DRIVE to upload self-viva, you a public platform like loom or upload on YouTube and `unlist` the video.

**Comment by th3c0d3br34ker** [comment]
approved during viva. please re-submit on kalvium.community and let me know.

please go ahead and merge this PR.

**Review by th3c0d3br34ker — APPROVED** [review]

**Pull request merged**
