### PR TITLE
Schema & ERD

### PR DESCRIPTION
**Pull request by Ahamed1846**
1. Added Schema diagram & ERD.
2. I have done an explanation of this PR [here](https://drive.google.com/file/d/1YPVJYJWkn3FkEoW1A20ccgCe1vc9wrXb/view?usp=sharing).

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
First Proposal and submitted schema ERD are somewhat different.
No proper explanation is provided of how it works. And the necessity of each tables and attributes, with connections is lacking proper explanation.

**Comment by Ahamed1846** [comment]
> First Proposal and submitted schema ERD are somewhat different. No proper explanation is provided of how it works. And the necessity of each tables and attributes, with connections is lacking proper explanation.

Just a quick clarification - I did mention these changes after the proposal but before approval of the project.

**Comment by PRASANNAPATHI** [comment]
No ahamed, while approving, you explained about another table called archived, 
Now you have made it as an attribute in Task details table, and some structure is changed.

Even if it works, we need more explanation from you, the video lacks proper explanation of working,

Let's have a viva session,

**Comment by th3c0d3br34ker** [comment]
Approved during viva session New PR was raised #8 .

**Pull request merged**
